In [ ]:
### Actividad 1:
#######
# Cree una función llamada getInfo que reciba dos parámetros, un argumento es el nombre de
# un archivo csv, y el segundo argumento el nombre de una columna. La función leerá el
# archivo (asuma que el nombre siempre es correcto), y devolverá una **lista** con toda la
# información de la columna solicitada. En caso que el nombre de la columna no exista se
# devolverá una lista vacía.
##########



### Actividad 2:
#######
# Cree una función llamada makeHistogram que reciba una lista y genere información dela
# lista recibida. En caso que los datos sean numéricos, se imprimirá por pantalla: el mínimo,
# promedio y desviación estándar, y el máximo de la lista. En caso que sea una lista de strings,
# se mostrará por pantalla el histograma ordenado en forma alfabética. Si la lista está vacía,
# entonces mostrará por pantalla lista vacía..
##########



#### Actividad 3:
## Reúna las funciones construidas en las actividades anteriores en un módulo llamado
# “Tarea2.py”. Agregue a su módulo instrucciones que se activen solo cuando se ejecuta
# directamente el módulo (es decir, que no aparezca cuando el módulo es importado)
##

if __name__ == "__main__":

In [16]:
import pandas as pd
import numpy as np
def getInfo (archivo, columna):
    """archivo en csv y nombre de columna"""
    data_frame = pd.read_csv(archivo, header=0, sep=",", encoding="utf-8")
    if columna not in data_frame.columns:
        return "Lista Vacía"
    ## Generar descripción de columna
    datos_columna = data_frame[columna].value_counts()
  
    ## Verificar si es numérica
    lista = datos_columna.tolist()
  
    ## Si es numérica, convertir a float 
    for estado in lista:
        try:
            float(estado)
        except ValueError:
            return lista
## Si no es numérica, devolver lista
    return [float(i) for i in lista]

In [2]:
def makeHistogram(lista):
    """
    En caso valores numéricos, estadísticas básicas.
    En caso valores no numéricos (categóricos), histograma frecuencia.
    """
    if not lista:
        return "Lista Vacía"
    
    # Comprobamos si la lista contiene valores numéricos o no
    try:
        valores = np.array(lista, dtype=float)
        
        # Calculamos las estadísticas básicas
        minimo = np.min(valores)
        promedio = np.mean(valores)
        desv_estandar = np.std(valores)
        maximo = np.max(valores)
        
        # Mostramos las estadísticas básicas en pantalla
        print(f"Mínimo de la lista: {minimo:.2f}")
        print(f"Promedio de la lista: {promedio:.2f}")
        print(f"Desviación estándar de la lista: {desv_estandar:.2f}")
        print(f"Máximo de la lista: {maximo:.2f}")
        
    except ValueError:
        # Histograma de frecuencias, por valores categóricos
        serie = pd.Series(lista).astype(str)
        histograma = serie.value_counts()
        
        for elemento, frecuencia in histograma.items():
            print(f"{elemento}: {frecuencia}")

In [9]:
    archivo = "DatosT2.csv"
    columna = "marital.status"
    lista = getInfo(archivo, columna)
    makeHistogram(lista)

20: 1
4: 1
Married-civ-spouse: 1
14: 1

In [18]:
data_frame = pd.read_csv(archivo, header=0, sep=",", encoding="utf-8")
data_frame

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,58,Local-gov,217775,—,—,Married-civ-spouse,Exec-managerial,Husband,White,Male,7298,0,40,United-States,>50K
1,29,Private,211482,—,—,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
2,36,Federal-gov,403489,—,—,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,>50K
3,42,Private,211253,—,—,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,<=50K
4,38,Self-emp-inc,159179,—,—,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,>50K
5,23,Private,214542,—,—,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
6,41,Private,67339,—,—,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,?,<=50K
7,38,Local-gov,286405,—,—,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,1887,50,United-States,>50K
8,31,Private,397467,—,—,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
9,41,Private,196456,—,—,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States,<=50K
10,57,Private,153918,—,—,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
11,37,Private,89559,—,—,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
12,59,Private,159008,—,—,Married-civ-spouse,Craft-repair,Husband,White,Male,7298,0,20,United-States,>50K
13,50,Private,31014,—,—,Married-civ-spouse,Prof-specialty,Wife,White,Female,0,0,40,United-States,>50K
14,43,Private,199191,—,—,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,50,United-States,<=50K
15,46,Private,146919,—,—,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,>50K
16,41,Self-emp-not-inc,142725,—,—,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,45,United-States,<=50K
17,61,Local-gov,35001,—,—,Married-civ-spouse,Adm-clerical,Husband,White,Male,2885,0,40,United-States,<=50K
18,36,Private,149833,—,—,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
19,42,Private,297335,—,—,Married-spouse-absent,Exec-managerial,Unmarried,Asian-Pac-Islander,Female,0,0,31,Laos,<=50K

In [19]:
datos_columna = data_frame[columna].value_counts()
datos_columna

Married-civ-spouse       14
Never-married             3
Divorced                  2
Married-spouse-absent     1
Name: marital.status, dtype: int64

In [17]:
lista = getInfo (archivo, columna)
lista

[14.0, 3.0, 2.0, 1.0]